### PR TITLE
allow batch size greater than 100

### PR DESCRIPTION
**Pull request by charlierudolph**

### CODE REVIEW

**Comment by charlierudolph** [comment]
@jcenturion any thoughts?

**Comment by jcenturion** [comment]
I like it. I will merge it after testing it. Thanks @charlierudolph.

**Comment by charlierudolph** [comment]
@jcenturion have you gotten a chance to test this?

**Comment by jcenturion** [comment]
@charlierudolph: Already merged. Thanks for your contribution.

**Pull request merged**
