### PR TITLE
Configurable max run time

### PR DESCRIPTION
**Pull request by svadla-oc**

### CODE REVIEW

**Comment by svadla-oc** [comment]
Addresses https://github.com/auth0/auth0-authentication-api-webhooks/issues/14.

**Comment by svadla-oc** [comment]
Please review and merge it asap as this issue is affecting us in production.

**Comment by fyockm** [comment]
@svadla-oc thanks for the PR. this issue is affecting a number of users, and an effort is underway internally to solve. while this solution might fix the problem for you, it could also exacerbate latency for others. will keep you posted and merge if this is deemed to be the correct approach.

**Comment by svadla-oc** [comment]
@fyockm thanks for the response. Any ETA on the solution? Could you elaborate on why this fix could result in latency for others? Is the concern that people can set this timeout to longer than the job frequency?
While I wait for a fix to be merged, is it possible for me to install a custom version of this extension from my forked repo? I tried installing the extension from the Auth0 UI using the url of my github repo but it didn't seem to install properly.

**Comment by fyockm** [comment]
closing in favor of #17

**Pull request closed without merging**
